@role_id=7dcabfde-8c70-4ce1-9c39-9208a754fe78

### Create a Role
POST {{url}}:{{port}}/{{api-version}}/roles

{
    "name":"Redator",
    "description":""
}

### Get All Roles
GET {{url}}:{{port}}/{{api-version}}/roles
    #?filter=name:tor
    #?order=-name
    #?skip=0&take=1

### Get a Role Details
GET {{url}}:{{port}}/{{api-version}}/roles/{{role_id}}

### Get a Role Users
GET {{url}}:{{port}}/{{api-version}}/roles/{{role_id}}/users

### Update a Role
PUT {{url}}:{{port}}/{{api-version}}/roles/{{role_id}}

{
    "name": "Editor"
}

### Delete a Role
DELETE  {{url}}:{{port}}/{{api-version}}/roles/{{role_id}}